btre/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts' # registering a namespace 

urlpatterns = [
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('vse_zayavki/',views.vse_zayavki, name='vse_zayvki'),

] 

btre/btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/',include('listings.urls')),
    path('accounts/',include('accounts.urls')),
    # path('contacts/',include('contacts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

btre/templates/partials/_alerts.html
{% if messages %}

    {%  for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" 
            role="alert">
                <button type="button" class="close" data-dismiss="alert"><span area-hidden='true'>&times;</span></button>
                <strong>
                   {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} 
                        Ошибка: 
                   {% else %}
                        {{  message.tags |title  }}
                   {% endif %}
                </strong>
                        {{ message }}
            </div>

        </div>
    {% endfor %}

{% endif %}

btre/templates/partials/_footer.html
<!--footer-->

<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> BT Real Estate
</footer>

btre/templates/partials/_navbar.html
 {% load static %}
 {% load auth_extras %}
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{%  url 'index' %}">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li class="nav-item mr-3 {% if request.resolver_match.url_name == 'index' %}active{% endif %}">
            <a class="nav-link" href="{%  url 'index' %}">Домой</a>
          </li>
          <li class="nav-item mr-3 {% if 'about' in request.path %}active{% endif %}" >
            <a class="nav-link" href="{% url 'about' %}">О компании</a>
          </li>
          <li class="nav-item mr-3 {% if request.resolver_match.url_name == 'listings'%}active{% endif %}  %}">
            <a class="nav-link" href="{% url 'listings'  %}">Объекты в продаже</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li 
            {% if 'dashboard' in request.path %}
              class='nav-item active mr-3'
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href="{% url 'accounts:dashboard' %}"> <!--go tu urls.py files and find register name-->
                Мои заявки {{ user.username }}</a>
            </li>
            <li class="nav-item mr-3">
              <a href="javascript:{document.getElementById('logout').submit()}"
              class="nav-link">
                <i class='fas.fa-sign-out-alt'></i>Logout
              </a>
              <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
                {% csrf_token %}
                <input type="hidden" >
              </form>   

            </li>
            
            
          {% else %}
            <li 
            {% if 'register' in request.path %}
              class='nav-item active mr-3'
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href="{% url 'accounts:register' %}"> <!--go tu urls.py files and find register name-->
                <i class="fas fa-user-plus"></i> Register</a>
            </li>
            <li 
            {% if 'login' in request.path %}
              class='nav-item active mr-3'
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href="{% url 'accounts:login' %}">
                <i class="fas fa-sign-in-alt"></i>
                Login</a>
            </li>

            {% endif %}

            {% if request.user|has_group:"Sellers" %}
            <li 
            {% if 'vse_zayavki' in request.path %}
              class='nav-item active mr-3'
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href="{% url 'accounts:vse_zayvki' %}"> 
                Все заявки </a>
            </li>

            {% else %} 

            {% endif %}
        
        </ul>
      </div>
    </div>
  </nav>

btre/templates/partials/_topbar.html
     <!-- Top Bar -->
     <section id="top-bar" class="p-3">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <i class="fas fa-phone"></i> (617)-555-5555
            </div>
            <div class="col-md-4">
              <i class="fas fa-envelope-open"></i> contact@btrealestate.co
            </div>
            <div class="col-md-4">
              <div class="social text-right">
                <a href="#">
                  <i class="fab fa-twitter"></i>
                </a>
                <a href="#">
                  <i class="fab fa-facebook"></i>
                </a>
                <a href="#">
                  <i class="fab fa-linkedin"></i>
                </a>
                <a href="#">
                  <i class="fab fa-instagram"></i>
                </a>
                <a href="#">
                  <i class="fab fa-pinterest"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>